Answer
geoffrey112/Exercices pull request #1
Opened 2020-11-17 16:11 UTC by geoffrey112

2020-11-17 21:49 UTC, wehrli requested changes
It is a very good start, you manage to use the javascript library ;) well use of `includes` & `toFixed`.
You hesitate sometimes about how to code it. Well I guess here it is just a matter of how you like it. There is debate on that anyway. I personally prefer to be easy to read. I can show you at the meeting ;) 
Nice implementation of the result through the html, I just regret that i had no way to put new value from it 😞

Most of your methods are not protected against unwanted value, like if put an `int` as parameters, rather than a `string`. YOU MUST ALWAYS VERIFY IT IS A WANTED VALUE

2020-11-17 21:49 UTC, wehrli commented on Functions/README.md
> +1. Create a function which take a number as parameters and return 'true' if it is a pair number and 'false' when it is odd
Thank you 🙏

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +  return date;
Here you return the date non-formatted.
**you got**: `Tue Nov 17 2020 15:30:00 GMT+0000 (Greenwich Mean Time)`
**expected**: `Tuesday 17 November 2020, 3:30pm`

Click [here](https://www.w3schools.com/js/js_date_formats.asp) 😉

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +}
nice use of `navigator.appVersion`, this was the solution ;)

For a better optimisation you could have use an [enum and a switch](https://www.sohamkamani.com/blog/2017/08/21/enums-in-javascript/)

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +  // return Math.PI.toFixed(nb); // Other answer
both technique works, but one is more readable than the other. 😉

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +function checkNumber(nb){
🥇

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +  // But what is the best answer?
which one it is according to you ? 🤔

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +  return string.split(" ");
a bit too static according to me, what if we want to accept multiple separator? 

[regexp](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/RegExp)

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +function returnObject(string){
you fell into my trap 😈 

read [that](https://www.w3schools.com/js/js_json_intro.asp) first
and [that](https://www.w3schools.com/js/js_json_parse.asp), very important as a web developper

2020-11-17 21:49 UTC, wehrli commented on Functions/src/js/func.js
> +// console.log(replace);
Look at you code deeply, read it out loud. the answer is under your eyes 🔍

2020-12-05 14:09 UTC, wehrli reviewed
way more better, nice job !

remarks: 
- On the index html put a title or a description per exercice (I know each one of them, but think of the fact that a lambda user could use your app)
- You need to give a better naming for each value you are creating. string2, button1, input4 that's not enough representative of what this variable id for.

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  let day = new Date().getDay();
In here it is a working algorithm nice ! 

now you could have use more the Date library to do it in 2 or three line (aka `toLocaleDateString` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

Also you are creating new Date everytime, you could have done
```
const date = new Date();
const day = date.getDay();
const month = date..getMonth();
....
```

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +let invalidChars = ["e", "E", "+", ",", "."];
why the letter `e` is invalid char ?

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  let answer = document.getElementById("checkNb").innerHTML = nb % 2 == false;
no need to create the variable answer here if you are not using it ;)

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  let answer = document.getElementById("reverse").innerHTML = input.split("").reverse().join("");
same here no need of the variable answer

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  console.log(array);
leftover :p

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  array = document.getElementById("inputArray").value.split(/[,]/g);
`/[,]/` beggining of using regexp ! nice !

2020-12-05 14:09 UTC, wehrli commented on Functions/src/js/func.js
> +  console.log(string.split(" "));
leftover :p

2020-12-05 14:09 UTC, wehrli commented on Functions/src/views/index.html
> +              <button class="btn btn-outline-primary btn-sm" type="button" id="checkLength">Lenght</button>
```suggestion
              <button class="btn btn-outline-primary btn-sm" type="button" id="checkLength">Length</button>
```

2020-12-05 14:09 UTC, wehrli commented on Functions/src/views/index.html
> +              <button class="btn btn-outline-primary btn-sm" type="button" id="lengthArray">Lenght of array</button>
```suggestion
              <button class="btn btn-outline-primary btn-sm" type="button" id="lengthArray">Length of array</button>
```

2020-12-06 22:39 UTC, wehrli approved these changes

2020-12-06 22:40 UTC, wehrli commented
you can fix the things I mentioned if you feel like :), but don't forget to merge what you've done with master

2020-12-07 14:53 UTC, geoffrey112 commented on Functions/src/js/func.js
> +let invalidChars = ["e", "E", "+", ",", "."];
Because i only want the int 🧐

2020-12-07 14:57 UTC, geoffrey112 commented on Functions/src/js/func.js
> +  let answer = document.getElementById("checkNb").innerHTML = nb % 2 == false;
Oups, Okey 👍

2020-12-07 15:00 UTC, geoffrey112 commented on Functions/src/js/func.js
> +  console.log(array);
My bad🤦‍♂️

2020-12-07 15:18 UTC, geoffrey112 commented on Functions/src/js/func.js
> +function returnObject(string){
Okey 🙂👍

2020-12-08 12:33 UTC, wehrli commented on Functions/src/js/func.js
> +let invalidChars = ["e", "E", "+", ",", "."];
okay but here you are blocking only the letter `e` so it is not bullet proof ^^. You want to use regexp here

2021-09-07 10:26 UTC, merged